export const actions = {
  SETTING_CURRENT_DAY_DATA: 'SETTING_CURRENT_DAY_DATA',
  SETTING_FORECAST_DAYS_DATA: 'SETTING_FORECAST_DAYS_DATA',
  SHOW_LOADING: 'SHOW_LOADING',
  SHOW_SEARCH_FORM: 'SHOW_SEARCH_FORM',
  SHOW_ERROR_MESSAGE: 'SHOW_ERROR_MESSAGE',
};
